### ISSUE TITLE
Not so much of an issue but a request! :)

### ISSUE THREAD

**Issue by Nashismo** [revvv/snes9xgx-retrode#1]
First, let me thank you for this, your work is really amazing!

I am also a HUGE fan playing old consoles on the Wii!! I think it is the BEST experience as the Wii supports 240p and it can be a lagless ideal experience using a CRT!

I saw on Github you have helped developing new USB controllers to work on Wii Retroarch! In summary what you have done is what I dream to do, but I do not have the expertise behind it.

What I would love to see being added to Retroarch Wii would be more options to use more controllers! My dream is to be able to use the Hori PC Engine controller!! To play those beautiful PC Engine games at 240p!!

https://www.amazon.com/-/es/Official-Turbo-Controller-Turbografx-16-Mini-HORI/dp/B07V1Q2G8T/ref=sr_1_1?__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=hori+pc+engine+controller&qid=1627791464&sr=8-1

This would be ideal as the PC Engine mini as well as the original console, are both hard to find and expensive when you do.

My best regards and tell me what you think of this idea! Or maybe this controller is working already on Retroarch Wii and I simply don't know!! :)

**Comment by revvv** [comment]
> First, let me thank you for this, your work is really amazing!

Thank you!

> My dream is to be able to use the Hori PC Engine controller!
> Or maybe this controller is working already on Retroarch Wii and I simply don't know!! :)

Looks like, it's already supported:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/9c27a99c177d5e0545f2d85f12cb7634b8f2e188/dinput/PCEngine%20PAD.cfg

Try with Windows version first...
